config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :bundles, only: [:show]
  resources :builds , only: [:new, :create, :show]
  resources :devices, only: [:new, :create, :show, :index] do
    post :create_mobileconfig, on: :collection
  end

  get   'admin'         => 'admin#index'
  post  'admin/enable'  => 'admin#enable'
  post  'admin/disable' => 'admin#disable'
end

app/models/build.rb
class Build < ActiveRecord::Base
  mount_uploader :file, FileUploader
  belongs_to :bundle,     inverse_of: :builds
  has_many   :provisions, inverse_of: :build

  def self.create_from_plist(plist)
    bundle_id = plist['CFBundleIdentifier']
    version   = plist['CFBundleShortVersionString']
    build_num = plist['CFBundleVersion']
    name      = plist['CFBundleName']

    bundle = Bundle.find_or_create_by(identifier: bundle_id) do |b|
      b.name = name
    end

    self.create(version: version, build: build_num, bundle: bundle)
  end
end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
  has_many :builds, inverse_of: :bundle
end

app/models/device.rb
require 'securerandom'

class Device < ActiveRecord::Base
  def self.create_from_plist(plist, owner = nil)
    # Find or create
    created = false
    device = self.find_or_create_by(udid: plist['UDID']) do |d|
      d.token = SecureRandom.urlsafe_base64(32)
      created = true
    end
    # Update device info
    device.update({
      version: plist['VERSION'],
      serial:  plist['SERIAL'],
      product: plist['PRODUCT'],
      owner:   owner
    })
    # Regenerate token if not first time
    unless created
      device.update(token: SecureRandom.urlsafe_base64(32))
    end
    device
  end
end

app/models/provision.rb
class Provision < ActiveRecord::Base
  belongs_to :build, inverse_of: :provisions
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
  end

  def enable
    if params[:admin_token].to_s == ENV['ADMIN_TOKEN'].to_s
      session[:is_admin] = 'Y'
      redirect_to root_path
    else
      redirect_to admin_path, alert: 'Admin token mismatch'
    end
  end

  def disable
    session[:is_admin] = nil
    redirect_to root_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :authenticate_device
  before_action :authenticate_admin

  def validate_useragent
    # Skip UA validation if not html
    return if request.format != 'text/html'
    bad = false
    if request.user_agent.to_s.include?('MicroMessenger')
      bad = true
    else
      ua = UserAgent.parse(request.user_agent)
      bad_browser = ua.browser != 'Safari'
      bad_platform= !['iPhone', 'iPad', 'iPod'].include?(ua.platform)
      bad = bad_browser || bad_platform
    end
    @is_ua_bad = bad
  end

  def authenticate_admin
    return if @admin_authenticated == true
    @is_admin = (session[:is_admin].to_s == 'Y') || ENV['ADMIN_TOKEN'].blank?
    @admin_authenticated = true
  end

  def authenticate_admin!
    authenticate_admin
    unless @is_admin
      redirect_to root_path, alert: t('ashe.no_permission')
    end
  end

  def authenticate_device
    return if @device_authenticated == true
    if session[:token].blank?
      session[:token] = params[:token]
    end

    unless session[:token].blank?
      @current_device = Device.find_by_token session[:token]
    end
    @device_authenticated = true
  end

  def authenticate_device!
    authenticate_device
    if @current_device.nil?
      redirect_to new_device_path, alert: t('ashe.please_register_device')
    end
  end

  def set_locale
    I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  end
end

app/controllers/builds_controller.rb
require 'uri'

require 'zip'
require 'cfpropertylist'

class BuildsController < ApplicationController
  before_action :validate_useragent,    only: [:show]
  before_action :authenticate_admin!,   only: [:new, :create]

  def new
  end

  def create
    form_params = params.require(:build).permit(:file, :desc)
    file = form_params[:file]
    desc = form_params[:desc]

    if file
      # Open zip file
      Zip::File.open(file.path) do |zip_file|
        # Get Info.plist and create build
        plist_entry = zip_file.glob("**/*.app/Info.plist").first
        if plist_entry
          plist = CFPropertyList::List.new({ data: plist_entry.get_input_stream.read.to_s,
                                             format: CFPropertyList::List::FORMAT_BINARY })
          @build = Build.create_from_plist CFPropertyList.native_types plist.value
          @build.file = file
          @build.desc = desc
          @build.save
        end
        # Get embedded.mobileprovision and record provisioned devices
        if @build
          provi_entry = zip_file.glob("**/*.app/embedded.mobileprovision").first
          if provi_entry
            provi = P7sPlist.parse provi_entry.get_input_stream.read.to_s
            if provi 
              devices = provi['ProvisionedDevices']
              if devices.kind_of? Array
                devices.each do |device_udid|
                  @build.provisions.create(udid: device_udid)
                end
              end
            end
          end
        end
      end
    end

    if !@build
      redirect_to new_build_path, alert: 'Cannot create this build'
    else
      redirect_to action: :show, id: @build.id
    end
  end

  def show
    @build = Build.find(params[:id])
    @build_file_url = URI.join(request.url, @build.file_url).to_s
    @can_install = @current_device.present? and Provision.find_by(build_id: @build.id, udid: @current_device.udid).present?

    if @is_admin
      provisioned_udids = @build.provisions.map { |pv| pv.udid }
      @devices_both    = Device.where(udid: provisioned_udids)
      both_udids       = @devices_both.select(:udid).map { |d| d.udid }
      @devices_missing = Device.where.not(udid: provisioned_udids)
      @udids_extra     = provisioned_udids - both_udids
    end
  end

end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  def show
    @bundle = Bundle.find(params[:id])
  end
end

app/controllers/devices_controller.rb
require 'securerandom'

class DevicesController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create]

  before_action :validate_useragent,    only: [:new]
  before_action :authenticate_device!,  only: [:show]
  before_action :authenticate_admin!,   only: [:index]

  def index
    @devices = Device.all.order("id DESC")
  end

  def new
    if @current_device
      redirect_to device_path(@current_device)
    end
  end

  def create_mobileconfig
    if params[:owner].blank?
      redirect_to new_device_path, { alert: "Please input owner name" }
    else
      @callback_url = devices_url(owner: params[:owner])
    end
  end

  def create
    device = Device.create_from_plist(P7sPlist.parse(request.raw_post.to_s), params[:owner])
    redirect_to device_path(device, token: device.token), status: 301
  end

  def show
    @device = Device.find params[:id]
    if @device.id != @current_device.id
      redirect_to root_path, alert: 'No permission !'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def li_link(link_text, link_path, &block)
    if link_text.nil?
      content_tag(:li, class: ('active' if current_page?(link_path)) ) do
        link_to link_path, &block
      end
    else
      content_tag(:li, class: ('active' if current_page?(link_path)) ) do
        link_to link_text, link_path
      end
    end
  end

end

app/helpers/builds_helper.rb
module BuildsHelper
  def ipa_install_url(build)
    "itms-services://?action=download-manifest&url=#{build_url(build, format: :plist).html_safe}"
  end
end

app/helpers/bundles_helper.rb
module BundlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.slim
.page-header
  h2 Enable/Disable Admin

hr

.row
  .col-md-6
    - if @is_admin
      = link_to 'Disable', admin_disable_path, class: 'btn btn-danger', method: 'post'
    - else
      = form_tag admin_enable_path do
        .form-group
          label Admin Token
          = text_field_tag :admin_token, nil, class: 'form-control'
        .form-group
          = submit_tag 'Enable', class: 'btn btn-success'
.row
  .col-md-6

app/views/builds/new.html.slim
.page-header
  h2= t 'ashe.upload_ipa'

hr

.row
  .col-md-6
    = form_for Build.new do |f|
      .form-group
        label=t 'ashe.file'
        = f.file_field(:file, class: 'form-control')
      .form-group
        label=t 'ashe.description'
        = f.text_area(:desc, class: 'form-control')
      .form-group.text-center
        = f.submit(t('ashe.upload'), class: 'btn btn-success')

app/views/builds/show.html.slim
.page-header
  h1
    a href=bundle_path(@build.bundle)
      = @build.bundle.name
    small
      | &nbsp;&nbsp;
      = @build.bundle.identifier
  h2= "#{@build.version} (Build #{@build.build})"
  - @build.desc.to_s.each_line do |line|
    h3= line
hr

.row
  .col-md-12.text-center
    - if @current_device.present?
      - if @can_install
        - if @is_ua_bad
          h4.text-danger= t 'ashe.bad_ua'
        - else
          = link_to t('ashe.click_to_install'), ipa_install_url(@build), class: 'btn btn-success btn-lg'
      - else
        h4.text-danger= t 'ashe.no_provision'
    - else
        h4.text-danger= t 'ashe.please_register_device'
        br
        = link_to t('ashe.register_device'), new_device_path, class: 'btn btn-primary'
- if @is_admin
  hr
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading= t 'ashe.devices_both'
        table.table
          tr
            td UDID
            td Id
            td Owner
          - @devices_both.each do |d|
            tr
              td= d.udid
              td= d.id
              td= d.owner
        .panel-heading= t 'ashe.devices_missing'
        table.table
          tr
            td UDID
            td Id
            td Owner
          - @devices_missing.each do |d|
            tr
              td= d.udid
              td= d.id
              td= d.owner
        .panel-heading= t 'ashe.udids_extra'
        table.table
          tr
            td UDID
          - @udids_extra.each do |d|
            tr
              td= d

app/views/builds/show.plist.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>items</key>
    <array>
      <dict>
        <key>assets</key>
        <array>
          <dict>
            <key>kind</key>
            <string>software-package</string>
            <key>url</key>
            <string><%= @build_file_url %></string>
          </dict>
        </array>
        <key>metadata</key>
        <dict>
          <key>bundle-identifier</key>
          <string><%= @build.bundle.identifier %></string>
          <key>bundle-version</key>
          <string><%= @build.version %></string>
          <key>kind</key>
          <string>software</string>
          <key>title</key>
          <string><%= @build.bundle.name %></string>
        </dict>
      </dict>
    </array>
  </dict>
</plist>

app/views/bundles/show.html.slim
.page-header
  h1
    = @bundle.name
    small
      | &nbsp;&nbsp;
      = @bundle.identifier
hr

.row
  .col-md-6
    .panel.panel-default
      .list-group
        - @bundle.builds.order(:id, "DESC").each do |build|
          a.list-group-item href=build_path(build)
            h4.list-group-item-heading="#{build.version} (Build #{build.build})"
            p.list-group-item-text= build.desc
            p.text-right.text-muted=time_ago_in_words(build.updated_at)

app/views/devices/create_mobileconfig.mobileconfig.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>PayloadContent</key>
        <dict>
            <key>URL</key>
            <string><%= @callback_url %></string>
            <key>DeviceAttributes</key>
            <array>
                <string>UDID</string>
                <string>PRODUCT</string>
                <string>VERSION</string>
                <string>SERIAL</string>
            </array>
        </dict>
        <key>PayloadOrganization</key>
        <string>IslandZero/Ashe Project</string>
        <key>PayloadDisplayName</key>
        <string>Ashe Profile Service</string>
        <key>PayloadVersion</key>
        <integer>1</integer>
        <key>PayloadUUID</key>
        <string>26C7DD21-2DFE-4EE3-9FBD-41B0EC118F3F</string>
        <key>PayloadIdentifier</key>
        <string>com.island0.ashe.profile-service</string>
        <key>PayloadDescription</key>
        <string>This is a temporary profile to enroll your device for ad-hoc app distribution.</string>
        <key>PayloadType</key>
        <string>Profile Service</string>
    </dict>
</plist>

app/views/devices/index.html.slim
.page-header
  h2= t 'ashe.all_devices'

hr

.row
  .col-md-12
    table.table
      tr
        td Id
        td Owner
        td UDID
        td Product
        td UpdatedAt
      - @devices.each do |d|
        tr
          td= d.id
          td= d.owner
          td= d.udid
          td= d.product
          td= time_ago_in_words d.updated_at

app/views/devices/new.html.slim
.page-header
  h2=t 'ashe.register_device'

hr

.row
  .col-md-6
    - if @is_ua_bad
      h4.text-danger= t 'ashe.bad_ua'
    - else
      = form_tag create_mobileconfig_devices_path(format: :mobileconfig) do
        .form-group
          label=t 'ashe.owner_name'
          = text_field_tag :owner, nil, class: 'form-control'
        .form-group.text-center
          = submit_tag t("ashe.register_device"), class: 'btn btn-success'

app/views/devices/new.mobileconfig.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>PayloadContent</key>
        <dict>
            <key>URL</key>
            <string><%= @callback_url %></string>
            <key>DeviceAttributes</key>
            <array>
                <string>DEVICE_NAME</string>
                <string>UDID</string>
                <string>PRODUCT</string>
                <string>VERSION</string>
                <string>SERIAL</string>
            </array>
        </dict>
        <key>PayloadOrganization</key>
        <string>IslandZero/Ashe Project</string>
        <key>PayloadDisplayName</key>
        <string>Ashe Profile Service</string>
        <key>PayloadVersion</key>
        <integer>1</integer>
        <key>PayloadUUID</key>
        <string>47D5071B-7748-4349-9A4D-C4AF66A9C685</string>
        <key>PayloadIdentifier</key>
        <string>com.island0.ashe.profile-service</string>
        <key>PayloadDescription</key>
        <string>This is a temporary profile to enroll your device for ad-hoc app distribution.</string>
        <key>PayloadType</key>
        <string>Profile Service</string>
    </dict>
</plist>

app/views/devices/show.html.slim
.page-header
  h2= t 'ashe.device_registered'

hr

.row
  .col-md-6
    h4= t "ashe.device_meta.owner"
    h5.text-success= @device.owner
    h4= t "ashe.device_meta.UDID"
    h5.text-success= @device.udid
    h4= t "ashe.device_meta.product"
    h5.text-success= @device.product
    h4= t "ashe.device_meta.version"
    h5.text-success= @device.version

app/views/layouts/application.html.slim
doctype html
html
  head
    title= content_for(:title) || "Ashe AdHoc Center"
    meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"
    =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#main-navbar" aria-expanded="false"
            span.sr-only Toggle
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href=root_path Ashe
        .collapse.navbar-collapse#main-navbar
          ul.nav.navbar-nav
            - if @is_admin
              = li_link t('ashe.admin'), admin_path
              = li_link t('ashe.upload'), new_build_path
              = li_link t('ashe.all_devices'), devices_path
            - if @current_device
              = li_link t('ashe.my_device'), device_path(@current_device)
            - else
              = li_link t('ashe.register_device'), new_device_path
    - if flash.alert
      .container
        .row
          .col-md-6.col-md-offset-3
            .alert.alert-warning.alert-dismissable rol="alert"
              button type="button" class="close" data-dismiss="alert"
                span aria-hidden="true" &times;
                span class="sr-only" Close
              = flash.alert
    .container
      = yield

    .container
      hr
      .row
        .col-md-12.text-center
          p
            small.text-muted
              a href="https://github.com/IslandZero/Ashe" Github
              | &nbsp;/&nbsp;
              a href="https://blog.yanke.io" Blog
              | &nbsp;/&nbsp; 2015 YANKE Guo(Ryan)
          p

app/views/welcome/index.html.slim
.page-header
  h2= t 'ashe.welcome'
hr

- Bundle.find_each do |bundle|
  .row
    .col-md-12
      .jumbotron
        h2
          = bundle.name
          small
            = "  (#{bundle.builds.count.to_s} builds)"
        h3= bundle.identifier
        br
        p
          a.btn.btn-success href=bundle_path(bundle) =t 'ashe.click_to_view'

app/views/welcome/udid.html.slim
.page-header
  h2 Get your UDID

hr

.row
  .col-md-5.text-center
    = link_to 'Get UDID', udid_path(format: :mobileconfig)

app/views/welcome/udid.mobileconfig.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>PayloadContent</key>
        <dict>
            <key>URL</key>
            <string><%= @callback_url %></string>
            <key>DeviceAttributes</key>
            <array>
                <string>DEVICE_NAME</string>
                <string>UDID</string>
                <string>PRODUCT</string>
                <string>VERSION</string>
                <string>SERIAL</string>
            </array>
        </dict>
        <key>PayloadOrganization</key>
        <string>IslandZero/Ashe Project</string>
        <key>PayloadDisplayName</key>
        <string>Ashe Profile Service</string>
        <key>PayloadVersion</key>
        <integer>1</integer>
        <key>PayloadUUID</key>
        <string>47D5071B-7748-4349-9A4D-C4AF66A9C685</string>
        <key>PayloadIdentifier</key>
        <string>com.island0.ashe.profile-service</string>
        <key>PayloadDescription</key>
        <string>This is a temporary profile to enroll your device for ad-hoc app distribution.</string>
        <key>PayloadType</key>
        <string>Profile Service</string>
    </dict>
</plist>